### ISSUE TITLE
Should be able to edit title / description before submitting

### ISSUE THREAD

**Issue by duttakapil** [vinaypuppal/linklet-app#16] opened 2017-06-18 18:57 UTC
This is a feature suggestion. The user should be able to edit the title and the description of the link being added, prior to submitting. This is because many links do not fetch a relevant title and description and can be improved upon by the user.

**Comment by vinaypuppal** [comment] 2017-06-23 05:01
Duplicate of #15

**Closed as completed by vinaypuppal** 2017-06-23 05:01 UTC
