### ISSUE TITLE
Single User link

### ISSUE THREAD

**Issue by haskarb** [vinaypuppal/linklet-app#24] opened 2017-07-31 01:17 UTC
Hi! there is no feature of seeing all the links shared by single user.  The method of searching could be by git Username.

**Comment by vinaypuppal** [comment] 2017-07-31 12:05
Hi,
Its a duplicate of #10 issue, as we have more people submitting links it would be useful feature as pointed by others in that issue. So I will implement it next update.
Thanks for the suggestion.

**Closed as completed by vinaypuppal** 2017-07-31 12:05 UTC
